name: report

on:
  pull_request:
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     # checkout the repo
      - name: Report
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization":"token ${{ github.token }}" \
            https://api.github.com/repos/jyoungyun/basic/check-runs \
            -d '{"name":"hello","head_sha":"${{ github.head_ref }}"}'
